version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1000", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  cli:
    image: python:3.11-slim
    working_dir: /workspace
    entrypoint: ["bash", "-lc"]
    environment:
      - PYTHONPATH=/workspace/src
    volumes:
      - .:/workspace
    depends_on:
      - redis

volumes:
  redis-data:
